from typing_extensions import Buffer, SupportsInt

class Application:
    def __init__(self, name: str): ...
    def init(self, win_width: int, win_height: int): ...
    def should_close(self) -> bool: ...
    def quit(self): ...
    def get_now(self) -> float: ...
    def get_delta_time(self) -> float: ...
    def render(self) -> None: ...
    def set_clear_color(self, r: float, g: float, b: float, a:float): ...
    def get_current_input(self) -> int: ...
    def use_renderer(self, renderer: Renderer): ...

class Renderer:
    def __init__(self): ...
    def add_object(self, obj: Object): ...

class Object:
    def __init__(self, positions: Buffer, vertex_count: SupportsInt, indices: Buffer, shader_source_path: str): ...
    def add_layout_slot(self, type: str, size: int): ...
    def add_buffer_to_vertex_array(self): ...
    def set_shader_uniform_4f(self, name: str, float_x: float, float_y: float, float_z: float, float_w: float): ...
    def set_shader_uniform_mat_4f(self, name: str, matrix: Buffer): ...