from typing_extensions import Buffer, SupportsInt

class Application:
    def __init__(self, name: str, font: str): ...
    def init(self, win_width: int, win_height: int): ...
    def should_close(self) -> bool: ...
    def quit(self): ...
    def get_now(self) -> float: ...
    def get_delta_time(self) -> float: ...
    def render(self) -> None: ...
    def _native_add_text(self, text:str, scale: float, pos_x: float, pos_y: float) -> int: ...
    def remove_text(self, id: int): ...
    def set_clear_color(self, r: float, g: float, b: float, a: float): ...
    def is_key_down(self, key: str) -> bool: ...
    def was_key_pressed(self, key: str) -> bool: ...
    def was_key_released(self, key: str) -> bool: ...
    def use_renderer(self, renderer: Renderer): ...

class Renderer:
    def __init__(self): ...
    def add_object(self, obj: Object): ...

class Object:
    def __init__(self,
                 positions: Buffer,
                 vertex_count: SupportsInt,
                 indices: Buffer,
                 shader_source_path: str,
                 pos_x: float,
                 pos_y: float,
                 layer: int = 0): ...
    def add_layout_slot(self, type: str, size: int): ...
    def add_buffer_to_vertex_array(self): ...
    def set_shader_uniform_4f(self, name: str, float_x: float, float_y: float, float_z: float, float_w: float): ...
    def set_shader_uniform_mat_4f(self, name: str, matrix: Buffer): ...
    def _native_move(self, offset_x: float, offset_y: float): ...
    def _native_move_to(self, pos_x: float, pos_y: float): ...
    def set_texture(self, texture_source_path: str, slot: int): ...