from typing import TypeAlias

_vec2d: TypeAlias = tuple[float, float]
_color: TypeAlias = tuple[int, int, int]

class Application:
    def __init__(self, name: str, window_dimensions: _vec2d): ...
    def should_close(self) -> bool: ...
    def quit(self) : ...
    def get_now(self) -> float: ...
    def get_delta_time(self) -> float: ...
    def render(self) -> None: ...
    def set_background_color(self, r: int, g: int, b: int): ...
    def is_key_down(self, key: str) -> bool: ...
    def use_renderer(self, renderer: Renderer): ...

class Renderer:
    def __init__(self): ...
    def add_object(self, obj: Object): ...

class Object:
    __has_texture: bool

    def __init__(self,
                 pos: _vec2d,
                 size: _vec2d,
                 layer: int = 0,
                 has_texture: bool = False,
                 shader_source_path: str = "", ): ...
    def set_color(self, color: _color): ...
    def move(self, offset: _vec2d): ...
    def move_to(self, pos: _vec2d): ...
    def use_texture(self, path: str): ...
    def set_tint(self, tint: _color, strength: float = 1): ...