from typing_extensions import Buffer, SupportsInt

vec2d = tuple[float, float]

class Application:
    def __init__(self, name: str): ...
    def init(self, win_width: int, win_height: int): ...
    def should_close(self) -> bool: ...
    def quit(self) : ...
    def get_now(self) -> float: ...
    def get_delta_time(self) -> float: ...
    def render(self) -> None: ...
    def set_background_color(self, r: int, g: int, b: int): ...
    def get_current_input(self) -> int: ...
    def use_renderer(self, renderer: Renderer): ...

class Renderer:
    def __init__(self): ...
    def add_object(self, obj: Object): ...

class Object:
    def __init__(self,
                 size: vec2d,
                 pos: vec2d,
                 shader_source_path: str,
                 layer: int = 0,
                 has_texture: bool = False): ...
    def set_color(self, r: int, g: int, b:int): ...
    def move(self, offset: vec2d): ...
    def move_to(self, pos: vec2d): ...
    def use_texture(self, path: str): ...